const swaggerJsDoc = require("swagger-jsdoc");
const swaggerUi = require("swagger-ui-express");

const DisableTryItOutPlugin = function () {
  return {
    statePlugins: {
      spec: {
        wrapSelectors: {
          allowTryItOutFor: () => () => false,
        },
      },
    },
  };
};

const specOptions = {
  swaggerOptions: {
    plugins: [DisableTryItOutPlugin],
  },
};

const options = {
  swaggerDefinition: {
    info: {
      title: "REST API - Todo APP",
      version: "1.0.0",
      description:
        "Our Todo express API with autogenerated swagger documentation. ",
    },
    basePath: "/api",
  },
  apis: ["./docs/*.yaml"],
};

const swaggerDocs = swaggerJsDoc(options);

module.exports = { swaggerUi, swaggerDocs, specOptions };
